apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
        version: v-12345
    spec:
      containers:
      - name: net-app
        image: ACRURL/net-app:v-12345
        ports:
        - containerPort: 80
      #imagePullSecrets:
      #- name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: net-app
spec:
  type: LoadBalancer
  selector:
    app: net-app
  ports:
  - port: 80
    targetPort: 80
